### ISSUE TITLE
Error loading

### ISSUE THREAD

**Issue by vdruts** [GeorgLegato/Txt2Vectorgraphics#10]
Error loading script: txt2vectorgfx (1).py
Traceback (most recent call last):
  File "C:\Users\chlyw\Desktop\Automatic1111\modules\scripts.py", line 69, in load_scripts
    compiled = compile(text, path, 'exec')
  File "C:\Users\chlyw\Desktop\Automatic1111\scripts\txt2vectorgfx (1).py", line 70
    <title>Txt2Vectorgraphics/txt2vectorgfx.py at main · GeorgLegato/Txt2Vectorgraphics</title>
                                                       ^
SyntaxError: invalid character '·' (U+00B7)

**Comment by GeorgLegato** [comment]
try to copy/paste the RAW content of the file or better clone or download it via github gui
or click the icon "Copy Raw Content" upper right of the custom script and paste it as new file locally into your SD-installtion/Scripts/
