### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by Katmoget** [GeorgLegato/Txt2Vectorgraphics#14]
Hi 

I'm trying to use the script with my local automatic 1111 Webui. When I run it the png file is created and saved but the vector is not created and I'm getting the following error.
```
Error completing request:20,  3.02it/s]
Arguments: ('task(iymzucw57jfuq1k)', 'a cute little dog,', '', [], 16, 0, False, False, 1, 1, 7, 2866231904.0, -1.0, 0, 0, 0, False, 512, 512, False, 0.7, 2, 'Latent', 0, 0, 0, 3, False, 'keyword prompt', 'keyword1, keyword2', 'None', 'textual inversion first', False, False, False, False, '', 'None - prompt only', 'svg', True, True, False, 0.5, True, 16, True, 16, 1, '', 0, '', 0, '', True, False, False, False) {}
Traceback (most recent call last):
  File "C:\stable_diffusion\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "C:\stable_diffusion\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "C:\stable_diffusion\stable-diffusion-webui\modules\txt2img.py", line 49, in txt2img
    processed = modules.scripts.scripts_txt2img.run(p, *args)
  File "C:\stable_diffusion\stable-diffusion-webui\modules\scripts.py", line 347, in run
    processed = script.run(p, *script_args)
  File "C:\stable_diffusion\stable-diffusion-webui\scripts\txt2vectorgfx.py", line 115, in run
    assert len(files) > 0
AssertionError
```
I tried the default setting and various combinations but get the same error regardless of the settings. 
I also tried with different models. 

I'm using a local install with the following config :
Python revision: 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Dreambooth revision: 65d5a78abe8a132d40c88360d77670a6d9b7294e
SD-WebUI revision: d5ce044bcdd9593751d7e0ba28087247ff0b7926

[+] bitsandbytes version 0.35.0 installed.
[+] diffusers version 0.10.2 installed.
[+] transformers version 4.25.1 installed.
[+] xformers version 0.0.14.dev0 installed.
[+] torch version 1.13.1+cu117 installed.
[+] torchvision version 0.14.1+cu117 installed.
Launching Web UI with arguments: --xformers

Thanks

**Comment by mp3pintyo** [comment]
first fix the CUDA
It might cause a problem here too.
https://www.youtube.com/watch?v=O01BrQwOd-Q

**Comment by Katmoget** [comment]
Thanks I'll try that. I just updated the damn thing yesterday, took ages too.

**Comment by Katmoget** [comment]
Ok, I followed the instructions in the video. I have now:

Python revision: 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Dreambooth revision: 65d5a78abe8a132d40c88360d77670a6d9b7294e
SD-WebUI revision: d5ce044bcdd9593751d7e0ba28087247ff0b7926

Checking Dreambooth requirements...
[+] bitsandbytes version 0.35.0 installed.
[+] diffusers version 0.10.2 installed.
[+] transformers version 4.25.1 installed.
[+] xformers version 0.0.14.dev0 installed.
[+] torch version 1.13.1+cu116 installed.
[+] torchvision version 0.14.1+cu116 installed.
Launching Web UI with arguments: --xformers

but still received the same error : 

```
Arguments: ('task(79iu8p5v9mm9nn1)', 'a cute litle cat', '', [], 20, 0, False, False, 1, 1, 7, -1.0, -1.0, 0, 0, 0, False, 512, 512, False, 0.7, 2, 'Latent', 0, 0, 0, 3, True, 'keyword prompt', 'keyword1, keyword2', 'None', 'textual inversion first', False, False, False, False, '', 'Illustration', 'svg', True, True, False, 0.5, True, 16, True, 16, 1, '', 0, '', 0, '', True, False, False, False) {}
Traceback (most recent call last):
  File "C:\stable_diffusion\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "C:\stable_diffusion\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "C:\stable_diffusion\stable-diffusion-webui\modules\txt2img.py", line 49, in txt2img
    processed = modules.scripts.scripts_txt2img.run(p, *args)
  File "C:\stable_diffusion\stable-diffusion-webui\modules\scripts.py", line 347, in run
    processed = script.run(p, *script_args)
  File "C:\stable_diffusion\stable-diffusion-webui\scripts\txt2vectorgfx.py", line 115, in run
    assert len(files) > 0
AssertionError
```

**Comment by Katmoget** [comment]
any idea what could cause the issue ?

**Comment by Katmoget** [comment]
Hi, I managed to get it to work by changing the output folder back to the default settings.
