### ISSUE TITLE
Cannot get the script to work, fails on saving the image

### ISSUE THREAD

**Issue by thepixelabs** [GeorgLegato/Txt2Vectorgraphics#15]
Downloaded the script, installed python3-tk and potrace

I am using AUTOMATIC1111's webui and when I run i see the image gets generated but in the last steps it fails and drops the image from the UI with an error - 
> Exception: TXT2Vectorgraphics: Execution of Potrace failed, check filesystem, permissions, installation or settings (is image saving on?)
> Time taken: 4.27sTorch active/reserved: 3161/3678 MiB, Sys VRAM: 4713/14961 MiB (31.5%)
> 

In the shell i get - 

>   File "/home/ubuntu/stable-diffusion-webui/scripts/txt2vectorgfx.py", line 127, in run
>     fullofTPNG = fullfnPath.with_stem(fullfnPath.stem+ "_T")
> AttributeError: 'PosixPath' object has no attribute 'with_stem'

I have image saving turned on and if i don't use the script they get successfully saved to - 
/stable-diffusion-webui/outputs

Having coding knowledge myself i tried to retrace what's going on and i could understand why it couldn't enumerate the photos and get their path, as they are saved on the filesystem.. 

any idea what configuration or where should i look to fix this

**Comment by GeorgLegato** [comment]
check your python version ( which is used in the auto1111 environment) it should be 3.10.

referring to PosixPath' object has no attribute 'with_stem'
it depends on some particular version 
. 

try to add "python --version" in your webui-user.sh to see which version is really used in the auto1111 environment 


> Downloaded the script, installed python3-tk and potrace
> 
> 
> 
> I am using AUTOMATIC1111's webui and when I run i see the image gets generated but in the last steps it fails and drops the image from the UI with an error - 
> 
> > Exception: TXT2Vectorgraphics: Execution of Potrace failed, check filesystem, permissions, installation or settings (is image saving on?)
> 
> > Time taken: 4.27sTorch active/reserved: 3161/3678 MiB, Sys VRAM: 4713/14961 MiB (31.5%)
> 
> > 
> 
> 
> 
> In the shell i get - 
> 
> 
> 
> >   File "/home/ubuntu/stable-diffusion-webui/scripts/txt2vectorgfx.py", line 127, in run
> 
> >     fullofTPNG = fullfnPath.with_stem(fullfnPath.stem+ "_T")
> 
> > AttributeError: 'PosixPath' object has no attribute 'with_stem'
> 
> 
> 
> I have image saving turned on and if i don't use the script they get successfully saved to - 
> 
> /stable-diffusion-webui/outputs
> 
> 
> 
> Having coding knowledge myself i tried to retrace what's going on and i could understand why it couldn't enumerate the photos and get their path, as they are saved on the filesystem.. 
> 
> 
> 
> any idea what configuration or where should i look to fix this

**Comment by thepixelabs** [comment]
@GeorgLegato Thank you, I actually figured the "object has no attribute 'with_stem'" is received because no object exists in the variable..

Anyhow I arrived to the conclusion I might have a python issue just this moment, I tried installing invokeAI and I noticed in their Docs it doesn't support my python version, then i went to stable diffusion and it happens I'm not on their supported version as well 🤦 Then i stumbled here to see if there is a response, and yeah, same problem 🤣 
Anyhow, I'm running off an AWS machine, so I'm recreating it from a different AMI and i'm good to go.

Thanks again
