### ISSUE TITLE
WebUI won't load the script

### ISSUE THREAD

**Issue by delijoe79** [GeorgLegato/Txt2Vectorgraphics#2]
WebUI spitting out the following error when trying to load script:

Error loading script: txt2vectorgfx.py
Traceback (most recent call last):
  File "C:\SD\stable-diffusion-webui\modules\scripts.py", line 69, in load_scripts
    compiled = compile(text, path, 'exec')
  File "C:\SD\stable-diffusion-webui\scripts\txt2vectorgfx.py", line 68
    <title>Txt2Vectorgraphics/txt2vectorgfx.py at 4d89e53528b0a72713fea99b9d6e75ee99919b26 · GeorgLegato/Txt2Vectorgraphics</title>

**Comment by GeorgLegato** [comment]
this is not a runtime error of the custom script
i have to check on my pc a clean setup

**Comment by delijoe79** [comment]
I'm a dummy.  I downloaded the script wrong.  I needed to download the raw script file.  I hate github.
