### ISSUE TITLE
Colab issue

### ISSUE THREAD

**Issue by 1GirlUniversity** [GeorgLegato/Txt2Vectorgraphics#21]
Unfortunately, it doesn't work on Google Colab. It's a pity because I was really looking forward to testing it

![Capturar](https://user-images.githubusercontent.com/112584638/223770060-a9a458f1-0140-4c16-ace4-86aaf68f2854.PNG)

**Comment by GeorgLegato** [comment]
This is a very common error. People copy the source code from the (html)view of github, so you get the crazy "<!DcoType html>".
it is a python code and does should not contain such syntax of course.
in github goto "Raw"-view of the code and copy/paste or clone the repo, or download the file regularely.
Then you get a flawless file
