### ISSUE TITLE
Error thrown when executing

### ISSUE THREAD

**Issue by ciavolella** [GeorgLegato/Txt2Vectorgraphics#5]
File "C:\StableDiffusion\AUTOMATIC1111\scripts\txt2vectorgfx.py", line 84, in run
    args = [PO_TO_CALL,  "-b", poFormat, "-o", fullof, "--blacklevel", format(poThreshold, 'f')]
TypeError: unsupported format string passed to dict.__format__

Let me know if attaching any logs or anything will help.  My wife runs a craft business and half of her work uses svgs for stencils and vinyls, so this would be awesome to get running on my SD machine.

**Comment by GeorgLegato** [comment]
seems "format(poThreshold, 'f')" is called as dict.format.
I ll check. you can edit your script in that way to have a workaround:
`
args = [PO_TO_CALL, "-b", poFormat, "-o", fullof, "--blacklevel", "0.5"]
`
It disables the hhreshold-Parameter for you, which is actually not so important, rarely you will rerun same seed and adjust threshold, right?

btw, nice use case: stencils and vinyls, if you have examples what you do and or what could be improved, be welcome to share it with us here or me. Website?
